INSERT INTO country(id,name,description,logo) VALUES (1,'Austria',NULL,'austria.jpg');
INSERT INTO country(id,name,description,logo) VALUES (12,'Belgium',NULL,'belgium.jpg');
INSERT INTO country(id,name,description,logo) VALUES (23,'Bulgaria',NULL,'bulgaria.jpg');
INSERT INTO country(id,name,description,logo) VALUES (34,'Croatia',NULL,'croatia.jpg');
INSERT INTO country(id,name,description,logo) VALUES (45,'Cyprus',NULL,'cyprus.jpg');
INSERT INTO country(id,name,description,logo) VALUES (56,'Czech Republic',NULL,'czech.jpg');
INSERT INTO country(id,name,description,logo) VALUES (67,'Denmark',NULL,'denmark.jpg');
INSERT INTO country(id,name,description,logo) VALUES (78,'Estonia',NULL,'estonia.jpg');
INSERT INTO country(id,name,description,logo) VALUES (89,'Finland',NULL,'finland.jpg');
INSERT INTO country(id,name,description,logo) VALUES (100,'France',NULL,'france.jpg');
INSERT INTO country(id,name,description,logo) VALUES (111,'Germany',NULL,'germany.jpg');
INSERT INTO country(id,name,description,logo) VALUES (122,'Greece',NULL,'greece.jpg');
INSERT INTO country(id,name,description,logo) VALUES (133,'Hungary',NULL,'hungary.jpg');
INSERT INTO country(id,name,description,logo) VALUES (144,'Ireland',NULL,'ireland.jpg');
INSERT INTO country(id,name,description,logo) VALUES (155,'Italy',NULL,'italy.jpg');
INSERT INTO country(id,name,description,logo) VALUES (166,'Latvia',NULL,'latvia.jpg');
INSERT INTO country(id,name,description,logo) VALUES (177,'Lithuania',NULL,'lithuania.jpg');
INSERT INTO country(id,name,description,logo) VALUES (188,'Luxembourg',NULL,'luxembourg.jpg');
INSERT INTO country(id,name,description,logo) VALUES (199,'Malta',NULL,'malta.jpg');
INSERT INTO country(id,name,description,logo) VALUES (210,'Netherlands',NULL,'netherlands.jpg');
INSERT INTO country(id,name,description,logo) VALUES (221,'Poland',NULL,'poland.jpg');
INSERT INTO country(id,name,description,logo) VALUES (232,'Portugal',NULL,'portugal.jpg');
INSERT INTO country(id,name,description,logo) VALUES (243,'Romania',NULL,'romania.jpg');
INSERT INTO country(id,name,description,logo) VALUES (254,'Slovakia',NULL,'slovakia.jpg');
INSERT INTO country(id,name,description,logo) VALUES (265,'Slovenia',NULL,'slovenia.jpg');
INSERT INTO country(id,name,description,logo) VALUES (276,'Spain',NULL,'spain.jpg');
INSERT INTO country(id,name,description,logo) VALUES (287,'Sweden',NULL,'sweden.jpg');
INSERT INTO country(id,name,description,logo) VALUES (298,'United Kingdom',NULL,'united-kingdom.jpg');
