INSERT INTO sight(id,city,image_name,name,country_id) VALUES (2,NULL,'eisriesenwelt_cave.jpg','Eisriesenwelt Cave',1);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (3,NULL,'hochosterwitz_castle.jpg','Hochosterwitz Castle',1);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (4,NULL,'hofburg_imperial_palace.jpg','Hofburg Imperial Palace',1);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (5,NULL,'krems.jpg','Krems',1);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (6,NULL,'mirabell_palace.jpg','Mirabell Palace',1);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (7,NULL,'vienna_state_opera.jpg','State Opera',1);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (13,NULL,'grand-place.jpg','Grand Palace',12);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (14,NULL,'bruges.jpg','The Canals and Belfry of Bruges',12);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (15,NULL,'cathedral-of-saint-bavo.jpg','Cathedral of Saint Bavo',12);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (16,NULL,'gravensteen.jpg','Gravensteen and Old Town',12);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (17,NULL,'st-peters-church.jpg','St. Peter''s Church',12);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (18,NULL,'waterloo.jpg','Waterloo',12);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (35,NULL,'dubrovnik-old-town.jpg','Dubrovnik Old Town Walls',34);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (36,NULL,'plitvice-national-park-waterfall.jpg','Plitvice Lakes National Park',34);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (37,NULL,'romanesque-church.jpg','Zadar''s Romanesque Churches',34);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (38,NULL,'saint-domnius-cathedral.jpg','Diocletian''s Palace in Split',34);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (39,NULL,'trogir.jpg','Trogir',34);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (40,NULL,'zlatni-rat-beach.jpg','Zlatni Rat Beach',34);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (55,NULL,'eiffel-tower.jpg','Eiffel Tower',100);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (56,NULL,'loire-valley.jpg','Loire Valley Châteaux',100);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (57,NULL,'louvre-museum.jpg','Louvre Museum',100);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (58,NULL,'mont-saint-michel.jpg','Mont Saint-Michel',100);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (59,NULL,'notre-dame.jpg','Cathédrale Notre-Dame de Chartres',100);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (60,NULL,'versailles.jpg','Palace of Versailles',100);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (112,NULL,'brandenburg-gate.jpg','Berlin''s Brandenburg Gate',111);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (113,NULL,'black-forest.jpg','The Black Forest',111);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (114,NULL,'cologne-cathedral.jpg','Cologne Cathedral',111);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (115,NULL,'museum-island.jpg','Berlin''s Museum Island',111);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (116,NULL,'neuschwanstein-castle.jpg','The Ultimate Fairytale Castle: Neuschwanstein',111);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (117,NULL,'sanssouci-park-palace.jpg','Sanssouci Park and Palace',111);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (134,NULL,'cliff-wall.jpg','Amalfi Coast',155);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (135,NULL,'colosseum.jpg','Colosseum',155);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (136,NULL,'pompeii.jpg','Pompeii',155);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (137,NULL,'tower-of-pisa.jpg','Leaning Tower of Pisa',155);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (138,NULL,'vatican-city.jpg','Vatican City',155);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (139,NULL,'venice-canals.jpg','Venice Canals',155);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (156,NULL,'beaufort-castle.jpg','Beaufort Castle',188);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (157,NULL,'bock-cliff.jpg','The Bock Casements',188);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (158,NULL,'grand-ducal-palace.jpg','Grand Ducal Palace',188);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (159,NULL,'grand-duke-jean-museum.jpg','Grand Duke Jean Museum of Modern Art',188);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (160,NULL,'national-museum-of-history-and-art.jpg','National Museum of History and Art',188);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (161,NULL,'old-quarter.jpg','The Old Quarter of Luxembourg City',188);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (189,NULL,'buda-castle.jpg','Buda Castle',133);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (190,NULL,'buda-hills.jpg','Buda Hills',133);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (191,NULL,'aggtelek.jpg','Aggtelek National Park and Caves',133);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (192,NULL,'szechenyi-bath.jpg','Széchenyi Bath',133);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (193,NULL,'eger-castle.jpg','Eger Castle',133);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (194,NULL,'danube.jpg','The Danube',133);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (277,NULL,'granada-alhambra.jpg','The Alhambra and Generalife Gardens',276);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (278,NULL,'great-mosque-mezquita.jpg','The Great Mosque of Cordoba',276);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (279,NULL,'guggenheim-museum.jpg','Guggenheim Museum',276);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (280,NULL,'interior-sagrada-familia.jpg','Sagrada Familia and Gaudi Sites',276);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (281,NULL,'monasterio-de-san-lorenzo.jpg','San Lorenzo de El Escorial',276);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (282,NULL,'prado-museum.jpg','The Prado and Paseo del Artes',276);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (299,NULL,'canterbury-cathedral.jpg','Canterbury Cathedral',298);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (300,NULL,'city-of-bath.jpg','The Roman Baths and Georgian City of Bath',298);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (301,NULL,'historic-yorkshire.jpg','Historic Yorkshire',298);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (302,NULL,'lake-district-national-park.jpg','Lake District National Park',298);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (303,NULL,'stonehenge.jpg','Stonehenge',298);
INSERT INTO sight(id,city,image_name,name,country_id) VALUES (304,NULL,'tower-of-london.jpg','Tower of London',298);
