package com.codecool.countryguidebook.model;

public enum Language {
    GERMAN, DUTCH, BULGARIAN, CROATIAN, GREEK, TURKISH, ARMENIAN,
    CHEZ, SLOVAK, DANISH, ESTONIAN, FINNISH, SWEDISH, FRENCH,
    HUNGARIAN, IRISH, ENGLISH, ITALIAN, LATVIAN, LITHUANIAN,
    LUXEMBOURGISH, MALTESE, POLISH, PORTUGUESE, ROMANIAN, SLOVENE,
    SPANISH;
}
